fix pana ci step

diff --git a/.github/workflows/lockpick.yaml b/.github/workflows/lockpick.yaml
--- a/.github/workflows/lockpick.yaml
+++ b/.github/workflows/lockpick.yaml
@@ -50,7 +50,10 @@ jobs:
 
       - name: Verify Pub Score
         run: |
+          echo "Running pana..."
           PANA=$(dart pub global run pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
-          echo "score: $PANA_SCORE"
-          IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
-          if (( $SCORE < $TOTAL )); then echo "minimum score not met!"; exit 1; fi
+          echo "Done. Score: $PANA_SCORE"
+          if [[ $PANA_SCORE != "130/130" ]]; then
+            echo "Pana score is not 130/130. Failing build."
+            exit 1
+          fi
